apiVersion: v1
kind: Secret
metadata:
  name: core-runtime-secrets
  namespace: attestry
type: Opaque
stringData:
  DB_PASSWORD: change-me-rds-master-password
  REDIS_PASSWORD: change-me-redis-password
  AWS_ACCESS_KEY_ID: change-me
  AWS_SECRET_ACCESS_KEY: change-me
  INVITATION_SQS_ACCESS_KEY: change-me
  INVITATION_SQS_SECRET_KEY: change-me
