apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
  namespace: attestry
  labels:
    app.kubernetes.io/name: core
    app.kubernetes.io/part-of: attestry
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: core
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: core
        app.kubernetes.io/part-of: attestry
    spec:
      nodeSelector:
        workload: app-services
      imagePullSecrets:
        - name: ghcr-credentials
      containers:
        - name: core
          image: ghcr.io/attestry/app:6e9ddc43f14e
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: core-config
            - secretRef:
                name: core-runtime-secrets
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
