apiVersion: v1
kind: Service
metadata:
  name: attestry-redis-master
  namespace: attestry
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: attestry
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
