apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: core
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - attestry
  selector:
    matchLabels:
      app.kubernetes.io/name: core
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ledger
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - attestry
  selector:
    matchLabels:
      app.kubernetes.io/name: ledger
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
